<?php $flashMessenger = IfwZend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

<?php if ($flashMessenger->setNamespace('default')->hasMessages() || $flashMessenger->setNamespace('success')->hasMessages()): ?>
    <div id="message" class="updated">
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <p><?php echo $msg ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php if ($flashMessenger->setNamespace('error')->hasMessages()): ?>
    <div id="message" class="error">
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <p><?php echo $msg ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
